export const APP_SHELL_DOMAIN_CONTEXT_NAMES = [
  "runtimeThreadContext",
  "sessionIdentityContext",
  "workspaceCatalogContext",
  "gitSurfaceContext",
  "modeRoutingContext",
  "accountSurfaceContext",
  "dictationSurfaceContext",
  "workspaceNavigationContext",
  "composerContext",
  "layoutContext",
  "fileEditorContext",
  "settingsContext",
  "runtimeContext",
  "modelSelectionContext",
  "collaborationModeContext",
] as const;

export type AppShellDomainContextName =
  (typeof APP_SHELL_DOMAIN_CONTEXT_NAMES)[number];

export type AppShellDomainContextValue = Record<string, unknown>;

export type AppShellDomainContexts = {
  runtimeThreadContext: AppShellDomainContextValue;
  sessionIdentityContext: AppShellDomainContextValue;
  workspaceCatalogContext: AppShellDomainContextValue;
  gitSurfaceContext: AppShellDomainContextValue;
  modeRoutingContext: AppShellDomainContextValue;
  accountSurfaceContext: AppShellDomainContextValue;
  dictationSurfaceContext: AppShellDomainContextValue;
  workspaceNavigationContext: AppShellDomainContextValue;
  composerContext: AppShellDomainContextValue;
  layoutContext: AppShellDomainContextValue;
  fileEditorContext: AppShellDomainContextValue;
  settingsContext: AppShellDomainContextValue;
  runtimeContext: AppShellDomainContextValue;
  modelSelectionContext: AppShellDomainContextValue;
  collaborationModeContext: AppShellDomainContextValue;
};

export type AppShellLegacyFlatContext = Record<string, any>;

export type AppShellDomainContextSelection<
  TDomainName extends AppShellDomainContextName,
> = Pick<AppShellDomainContexts, TDomainName>;

export const APP_SHELL_DOMAIN_CONTEXT_OWNED_KEYS: Record<
  AppShellDomainContextName,
  readonly string[]
> = {
  runtimeThreadContext: [
    "runtimeThreadBoundary",
    // S4 bag-split PR-1：会话热路径（从 workspaceNavigation / settings 迁入）
    "activeItems",
    "activePlan",
    "activeRateLimits",
    "activeTokenUsage",
    "activeTurnId",
    "canInterrupt",
    "isProcessing",
    "isReviewing",
    "timelinePlan",
  ],
  sessionIdentityContext: [
    "RECENT_THREAD_LIMIT",
    "activeParentWorkspace",
    "activePath",
    "activeThreadId",
    "activeThreadIdForModeRef",
    "activeThreadIdRef",
    "activeWorkspace",
    "activeWorkspaceId",
    "activeWorkspaceIdRef",
    "activeWorkspaceRef",
    "activeWorkspaceThreads",
    "baseWorkspaceRef",
  ],
  workspaceCatalogContext: [
    "addCloneAgent",
    "addWorkspace",
    "addWorkspaceFromPath",
    "addWorktreeAgent",
    "assignWorkspaceGroup",
    "cancelClonePrompt",
    "cancelWorktreePrompt",
    "chooseCloneCopiesFolder",
    "clearCloneCopiesFolder",
    "clonePrompt",
    "closeWorktreeCreateResult",
    "confirmClonePrompt",
    "confirmRenameWorktreeUpstream",
    "confirmWorktreePrompt",
    "connectWorkspace",
    "createWorkspaceGroup",
    "deleteWorkspaceGroup",
    "deletingWorktreeIds",
    "directories",
    "directoryMetadata",
    "ensureWorkspaceThreadListLoaded",
    "forkThreadForWorkspace",
    "forkSessionFromMessageForWorkspace",
    "forkClaudeSessionFromMessageForWorkspace",
    "getWorkspaceGroupName",
    "getWorkspacePromptsDir",
    "repositories",
    "repositoriesLoading",
    "isMultiRepository",
  ],
  gitSurfaceContext: [
    "GitHubPanelData",
    "activeDiffError",
    "activeDiffLoading",
    "activeDiffs",
    "activeGitRoot",
    "activeGitHistoryTabId",
    "branchError",
    "branches",
    "checkoutBranch",
    "clearGitOperationErrors",
    "clearGitRootCandidates",
    "commitError",
    "commitLoading",
    "commitMessage",
    "commitMessageError",
    "commitMessageLoading",
    "confirmBranch",
    "confirmCommit",
    "createBranch",
    "currentBranch",
    "diffScrollRequestId",
    "diffSource",
    "exitDiffView",
    "fileStatus",
    "gitCommitDiffs",
    "gitDiffListView",
    "gitDiffViewStyle",
    "gitHistoryPanelHeight",
    "gitHistoryPanelHeightRef",
    "gitIssues",
    "gitIssuesError",
    "gitIssuesLoading",
    "gitIssuesTotal",
    "gitLogAhead",
    "gitLogAheadEntries",
    "gitLogBehind",
    "gitLogBehindEntries",
    "gitLogEntries",
    "gitLogError",
    "gitLogLoading",
    "gitLogTotal",
    "gitLogUpstream",
    "gitPanelMode",
    "gitPullRequestComments",
    "gitPullRequestCommentsError",
    "gitPullRequestCommentsLoading",
    "gitPullRequestDiffs",
    "gitPullRequestDiffsError",
    "gitPullRequestDiffsLoading",
    "gitPullRequests",
    "gitPullRequestsError",
    "gitPullRequestsLoading",
    "gitPullRequestsTotal",
    "gitRemoteUrl",
    "gitRootCandidates",
    "gitRootScanDepth",
    "gitRootScanError",
    "gitRootScanHasScanned",
    "gitRootScanLoading",
    "gitStatus",
    "gitignoredDirectories",
    "gitignoredFiles",
    "localBranches",
    "remoteBranches",
    "repositoryError",
    "repositoryStatuses",
    "repositoryStatusesLoading",
    "refreshRepositoryStatuses",
    "handleStageRepositoryFile",
    "handleUnstageRepositoryFile",
    "handleUnstageRepositoryAll",
    "handleUnstageRepositoryFiles",
    "handleRevertRepositoryFile",
    "handleRevertRepositoryFiles",
    "handleStageRepositoryAll",
    "handleCommitRepositories",
    "repositoryCommitSummary",
    "selectRepository",
    "selectedRepositoryRoot",
  ],
  modeRoutingContext: [
    "accessMode",
    "activeTab",
    "appMode",
    "centerMode",
    "claudeAccessModeRef",
    "filePanelMode",
    "showMarket",
  ],
  accountSurfaceContext: [
    "accountByWorkspace",
    "accountSwitching",
    "activeAccount",
    "approvals",
  ],
  dictationSurfaceContext: [
    "clearDictationError",
    "clearDictationHint",
    "clearDictationTranscript",
    "dictationError",
    "dictationHint",
    "dictationLevel",
    "dictationModel",
    "dictationReady",
    "dictationState",
    "dictationTranscript",
  ],
  workspaceNavigationContext: [
    "SettingsView",
    "activeEditorFilePath",
    "activeEditorLineRange",
    "activeEngine",
    "activeImages",
    "activeFusingMessageId",
    "fileCompareSession",
    "fileHistoryTabs",
    "activeQueue",
    "activeQueuedHandoffBubble",
    "activeRenamePrompt",
    "agentTaskScrollRequest",
    "activeTerminalId",
    "activeWorkspaceKanbanTasks",
    "addDebugEntry",
    "agent",
    "alertError",
    "appRootRef",
    "appSettings",
    "appSettingsLoading",
    "attachImages",
    "canFuseActiveQueue",
    "fuseDisabledReasonKey",
    "choosePreset",
    "claudeThinkingVisible",
    "clearActiveImages",
    "clearDebugEntries",
    "clearDraftForThread",
    "closePlanPanel",
    "checkForUpdates",
    "closeReleaseNotes",
    "closeReviewPrompt",
    "closeSettings",
    "closeTerminalPanel",
    "codexComposerModeRef",
    "collapseRightPanel",
    "collapseSidebar",
    "commands",
    "completionEmailIntentByThread",
    "completionTrackerBySessionRef",
    "completionTrackerReadyRef",
    "composerEditorSettings",
    "composerInputRef",
    "composerInsert",
    "confirmCustom",
    "createPrompt",
    "debugEntries",
    "debugOpen",
    "debugPanelHeight",
    "deletePrompt",
    "deleteThreadPrompt",
    "dismissErrorToast",
    "dismissUpdate",
    "doctor",
    "claudeDoctor",
    "kimiDoctor",
    "grokDoctor",
    "opencodeDoctor",
    "piDoctor",
    "editorHighlightTarget",
    "editorNavigationTarget",
    "editorSplitCompanion",
    "editorSplitLayout",
    "engineModelsAsOptions",
    "engineSelectedModelIdByType",
    "engineStatuses",
    "ensureLaunchTerminal",
    "ensureTerminalWithTitle",
    "errorToasts",
    "expandRightPanel",
    "expandSidebar",
    "fileReferenceMode",
    "fileTreeLoadError",
    "fileTreeSourceVersion",
    "files",
    "getGlobalPromptsDir",
    "getPinTimestamp",
    "getThreadRows",
    "globalSearchFilesByWorkspace",
  ],
  composerContext: [
    "groupedWorkspaces",
    "handleActivateFileTab",
    "handleActiveDiffPath",
    "handleAddAgent",
    "handleAddCloneAgent",
    "handleAddWorkspace",
    "handleOpenNewWindow",
    "handleAddWorkspaceFromPath",
    "handleAddWorktreeAgent",
    "handleAppModeChange",
    "handleApplyWorktreeChanges",
    "handleApprovalBatchAccept",
    "handleApprovalDecision",
    "handleApprovalRemember",
    "handleArchiveActiveThread",
    "handleCancelSwitchAccount",
    "handleCheckoutBranch",
    "handleCloseAllFileTabs",
    "handleCloseFileTab",
    "handleCloseOtherFileTabs",
    "handleCommit",
    "handleCommitAndPush",
    "handleCommitAndSync",
    "handleCommitMessageChange",
    "handleCopyDebug",
    "handleCopyThread",
    "handleCreateBranch",
    "handleCreatePrompt",
    "handleDebugClick",
    "handleDeletePrompt",
    "handleDeleteQueued",
    "handleDeleteThreadPromptCancel",
    "handleDeleteThreadPromptConfirm",
    "handleDraftChange",
    "handleDropWorkspacePaths",
    "handleEditQueued",
    "handleEnsureWorkspaceThreadsForSettings",
    "handleExitEditor",
    "handleGenerateCommitMessage",
    "handleGitIssuesChange",
    "handleGitPanelModeChange",
    "handleGitPullRequestCommentsChange",
    "handleGitPullRequestDiffsChange",
    "handleGitPullRequestsChange",
    "handleInsertComposerText",
    "handleLockPanel",
    "handleMovePrompt",
    "handleOpenDetachedFileExplorer",
    "handleOpenFile",
    "handleOpenWorkspaceFileCompare",
    "handleOpenScratchFileCompare",
    "handleCloseFileCompare",
    "handleOpenFileHistory",
    "handleActivateGitHistoryTab",
    "handleCloseFileHistory",
    "handleCloseOtherFileHistories",
    "handleCloseAllFileHistories",
    "handleOpenMailSession",
    "handleOpenModelSettings",
    "handleRefreshModelConfig",
    "handleReorderFileTabs",
    "handleOpenRenameWorktree",
    "handleResolvedClaudeThinkingVisibleChange",
    "handlePickGitRoot",
    "handlePush",
    "handleRenamePromptCancel",
    "handleRenamePromptChange",
    "handleRenamePromptConfirm",
    "handleRenameThread",
    "handleRenameWorktreeCancel",
    "handleRenameWorktreeChange",
    "handleRenameWorktreeConfirm",
    "handleRevealGeneralPrompts",
    "handleRevealWorkspacePrompts",
    "handleRevertAllGitChanges",
    "handleRevertGitFile",
    "handleRevertGitPaths",
    "handleReviewPromptKeyDown",
    "handleSelectAgent",
    "handleSelectCommit",
    "handleSelectDiff",
    "handleSelectModel",
    "handleSelectOpenAppId",
    "handleSelectOpenCodeAgent",
    "handleSelectOpenCodeVariant",
    "handleSelectStatusPanelSubagent",
    "handleSend",
    "handleSendPrompt",
    "handleSendPromptToNewAgent",
    "handleSetAccessMode",
    "handleSetGitRoot",
    "handleStageGitAll",
    "handleStageGitFile",
    "handleSwitchAccount",
    "handleFuseQueued",
    "handleSync",
    "handleTestNotificationSound",
    "handleToggleDictation",
    "handleToggleRuntimeConsole",
    "handleToggleTerminal",
    "handleToggleTerminalPanel",
    "handleUnlockPanel",
    "handleUnstageGitAll",
    "handleUnstageGitFile",
    "handleUnstageGitPaths",
    "handleUpdatePrompt",
    "handleUpdateBranch",
    "handleUpdateAllRepositories",
    "handleCheckoutAllRepositories",
    "handleLoadCommonRepositoryBranches",
    "handleUserInputSubmit",
    "handleUserInputSubmitWithPlanApply",
    "handleExitPlanModeExecute",
    "handleWorkspaceDragEnter",
    "handleWorkspaceDragLeave",
    "handleWorkspaceDragOver",
    "handleWorkspaceDrop",
    "handleWorktreeCreated",
    "hasActivePlan",
    "hasLoaded",
    "hasPlanData",
    "highlightedBranchIndex",
    "highlightedCommitIndex",
    "highlightedPresetIndex",
    "historySearchItems",
    "hydratedThreadListWorkspaceIds",
    "hydratedThreadListWorkspaceIdsRef",
    "availableEngines",
    "installedEngines",
    "interruptTurn",
    "isCompact",
    "isDeleteThreadPromptBusy",
    "isEditorFileMaximized",
    "isFilesLoading",
    "isMacDesktop",
    "isModelConfigRefreshing",
    "isPanelLocked",
    "isPhone",
    "isPlanMode",
    "isPlanPanelDismissed",
    "isSearchPaletteOpen",
  ],
  layoutContext: [
    "isTablet",
    "isThreadAutoNaming",
    "isThreadPinned",
    "isWindowsDesktop",
    "isWorkspaceDropActive",
    "isWorktreeWorkspace",
    "kanbanConversationWidth",
    "kanbanCreatePanel",
    "kanbanCreateTask",
    "kanbanDeletePanel",
    "kanbanDeleteTask",
    "kanbanPanels",
    "kanbanReorderTask",
    "kanbanTasks",
    "kanbanUpdatePanel",
    "kanbanUpdateTask",
    "kanbanViewState",
    "lastAgentMessageByThread",
    "lastCodexModeSyncThreadRef",
    "launchScriptState",
    "launchScriptsState",
    "listThreadsForWorkspace",
    "listThreadsForWorkspaceTracked",
    "liveEditPreviewEnabled",
    "loadOlderThreadsForWorkspace",
    "lockLiveSessions",
    "markWorkspaceConnected",
    "models",
    "movePrompt",
    "moveWorkspaceGroup",
    "navigateToThread",
    "handleOpenClaudeTui",
    "normalizePath",
    "onCloseTerminal",
    "onDebugPanelResizeStart",
    "onGitHistoryPanelResizeStart",
    "onKanbanConversationResizeStart",
    "onNewTerminal",
    "onPlanPanelResizeStart",
    "onRightPanelResizeStart",
    "onSelectTerminal",
    "onSidebarResizeStart",
    "onTerminalPanelResizeStart",
    "onTextareaHeightChange",
    "openAppIconById",
    "openClonePrompt",
    "openCodeAgents",
    "openDeleteThreadPrompt",
    "openFileTabs",
    "openPlanPanel",
    "openReleaseNotes",
    "openRenamePrompt",
    "openRenameWorktreePrompt",
    "openSettings",
    "openTerminal",
    "openWorktreePrompt",
    "perfSnapshotRef",
    "persistComposerSelectionForThread",
    "persistProjectCopiesFolder",
    "pickImages",
    "pinThread",
    "pinnedThreadsVersion",
    "planByThread",
    "planPanelHeight",
    "prefillDraft",
    "prompts",
    "pushError",
    "pushLoading",
    "queueGitStatusRefresh",
    "queueMessage",
    "queueSaveSettings",
    "rateLimitsByWorkspace",
    "recentThreads",
    "reduceTransparency",
    "windowTransparencyEnabled",
    "windowOpacity",
    "refreshAccountInfo",
    "refreshAccountRateLimits",
    "refreshEngines",
    "refreshFiles",
    "refreshGitDiffs",
    "refreshGitLog",
    "refreshGitStatus",
    "refreshThread",
    "refreshWorkspaces",
    "releaseNotesActiveIndex",
    "releaseNotesEntries",
    "releaseNotesError",
    "releaseNotesLoading",
    "releaseNotesOpen",
    "reloadSelectedAgent",
    "removeImage",
    "removeImagesForThread",
    "removeThread",
    "removeThreads",
    "removeWorkspace",
    "removeWorktree",
    "renamePrompt",
    "renameThread",
    "renameWorkspaceGroup",
    "renameWorktree",
    "renameWorktreeNotice",
    "renameWorktreePrompt",
  ],
  fileEditorContext: [
    "renameWorktreeUpstream",
    "renameWorktreeUpstreamPrompt",
    "resetGitHubPanelState",
    "resetSoloSplitToHalf",
    "resetWorkspaceThreads",
    "resolveCloneProjectContext",
    "resolveCanonicalThreadId",
    "resolveComposerSelectionForThread",
    "resolveOpenCodeAgentForThread",
    "resolveOpenCodeVariantForThread",
    "restartTerminalSession",
    "retryReleaseNotesLoad",
    "reviewPrompt",
    "rightPanelCollapsed",
    "rightPanelWidth",
    "scaleShortcutText",
    "scaleShortcutTitle",
    "scanGitRoots",
    "scopedKanbanTasks",
    "searchContentFilters",
    "searchApiHydrationStatus",
    "searchFileHydrationStatus",
    "searchPaletteQuery",
    "searchPaletteSelectedIndex",
    "searchResults",
    "searchScope",
    "selectBranch",
    "selectBranchAtIndex",
    "selectCommit",
    "selectCommitAtIndex",
    "selectHome",
    "selectWorkspace",
    "selectedAgent",
    "selectedCommitSha",
    "selectedDiffPath",
    "selectedAgentRef",
    "selectedKanbanTaskId",
    "selectedOpenCodeAgent",
    "selectedOpenCodeVariant",
    "selectedPullRequest",
    "sendUserMessage",
  ],
  settingsContext: [
    "sendUserMessageToThread",
    "setAccessMode",
    "setActiveEditorLineRange",
    "setActiveEngine",
    "setActiveTab",
    "setActiveThreadId",
    "setActiveWorkspaceId",
    "setAppMode",
    "setAppSettings",
    "setCenterMode",
    "setComposerInsert",
    "setDebugOpen",
    "setDiffSource",
    "setEditorSplitCompanion",
    "setEditorSplitLayout",
    "setEngineSelectedModelIdByType",
    "setFilePanelMode",
    "setFileReferenceMode",
    "setGitDiffListView",
    "setGitDiffViewStyle",
    "setGitHistoryPanelHeight",
    "setGitPanelMode",
    "setGitRootScanDepth",
    "setGlobalSearchFilesByWorkspace",
    "setHighlightedBranchIndex",
    "setHighlightedCommitIndex",
    "setHighlightedPresetIndex",
    "setIsEditorFileMaximized",
    "setIsPanelLocked",
    "setIsPlanPanelDismissed",
    "setIsSearchPaletteOpen",
    "setKanbanViewState",
    "setLiveEditPreviewEnabled",
    "setPrefillDraft",
    "setReduceTransparency",
    "setWindowTransparencyEnabled",
    "setWindowOpacity",
    "setRightPanelWidth",
    "setSearchContentFilters",
    "setSearchPaletteQuery",
    "setSearchPaletteSelectedIndex",
    "setSearchScope",
    "setSelectedCommitSha",
    "setSelectedDiffPath",
    "setSelectedKanbanTaskId",
    "setSelectedPullRequest",
    "setHomeOpen",
    "setWorkspaceHomeWorkspaceId",
    "settingsHighlightTarget",
    "settingsOpen",
    "settingsSection",
    "loadingProgressDialog",
    "dismissLoadingProgressDialog",
    "shouldLoadDiffs",
    "shouldLoadGitHubPanelData",
    "showLoadingProgressDialog",
    "hideLoadingProgressDialog",
    "showDebugButton",
    "showGitHistory",
    "showExtensions",
    "showHome",
    "showKanban",
    "showNextReleaseNotes",
    "showPresetStep",
    "showPreviousReleaseNotes",
    "showWorkspaceHome",
    "sidebarCollapsed",
    "sidebarWidth",
    "skills",
    "startCompact",
    "startExport",
    "startFast",
    "startFork",
    "startImport",
    "startLsp",
    "startMcp",
    "startMode",
    "startResume",
    "startReview",
    "startShare",
    "startSpecRoot",
    "startStatus",
    "startThreadForWorkspace",
    "startSharedSessionForWorkspace",
    "startUpdate",
    "syncError",
    "syncLoading",
    "t",
    "tabletTab",
    "terminalOpen",
    "terminalPanelHeight",
    "terminalState",
    "terminalTabs",
    "textareaHeight",
    "threadAccessMode",
    "threadItemsByThread",
    "threadListCursorByWorkspace",
    "threadListLoadingByWorkspace",
    "threadListPagingByWorkspace",
    "threadParentById",
    "threadStatusById",
    "historyLoadingByThreadId",
    "historyLoadingProgressByThreadId",
    "historyRestoredAtMsByThread",
    "threadsByWorkspace",
    "tokenUsageByThread",
    "toggleCompletionEmailIntent",
    "triggerAutoThreadTitle",
    "ungroupedLabel",
    "unpinThread",
    "updateThreadParent",
    "updateCloneCopyName",
    "updateCustomInstructions",
    "updatePrompt",
    "updateWorkspaceCodexBin",
    "updateWorkspaceSettings",
    "updateWorktreeBaseRef",
    "updateWorktreeBranch",
    "updateWorktreePublishToOrigin",
    "updateWorktreeSetupScript",
    "updaterState",
    "useSuggestedCloneCopiesFolder",
    "userInputRequests",
    "workspaceActivity",
    "workspaceDropTargetRef",
    "workspaceFilesPollingEnabled",
    "workspaceGroups",
    "workspaceHomeWorkspaceId",
    "workspaceNameByPath",
    "homeWorkspaceDefaultId",
    "homeWorkspaceSelectedId",
    "workspaceSearchSources",
    "workspaces",
    "workspacesById",
    "workspacesByPath",
    "worktreeApplyError",
    "worktreeApplyLoading",
    "worktreeApplySuccess",
    "worktreeCreateResult",
    "worktreeLabel",
    "worktreePrompt",
    "worktreeRename",
    "worktreeSetupScriptState",
    "sessionRadarRunningSessions",
    "sessionRadarRecentCompletedSessions",
    "runningSessionCountByWorkspaceId",
    "recentCompletedSessionCountByWorkspaceId",
  ],
  runtimeContext: [
    "runtimeRunState",
  ],
  modelSelectionContext: [
    "effectiveModels",
    "effectiveReasoningSupported",
    "effectiveSelectedModel",
    "effectiveSelectedModelId",
    "providerModelCatalogs",
    "reasoningOptions",
    "reasoningSupported",
    "refreshEngineModels",
    "resolvedEffort",
    "resolvedModel",
    "selectedEffort",
    "selectedModelId",
    "setSelectedEffort",
    "setSelectedModelId",
  ],
  collaborationModeContext: [
    "applySelectedCollaborationMode",
    "collaborationModePayload",
    "collaborationModes",
    "collaborationModesEnabled",
    "collaborationRuntimeModeByThread",
    "collaborationUiModeByThread",
    "handleCollaborationModeResolved",
    "resolveCollaborationRuntimeMode",
    "resolveCollaborationUiMode",
    "selectedCollaborationMode",
    "selectedCollaborationModeId",
    "setCodexCollaborationMode",
    "setCollaborationRuntimeModeByThread",
    "setCollaborationUiModeByThread",
    "setSelectedCollaborationModeId",
  ],
};

export function listAppShellDomainContextNames(): AppShellDomainContextName[] {
  return [...APP_SHELL_DOMAIN_CONTEXT_NAMES];
}

export function defineAppShellDomainContexts<T extends AppShellDomainContexts>(
  contexts: T,
): T {
  return contexts;
}

export function flattenAppShellDomainContexts(
  contexts: AppShellDomainContexts,
): AppShellLegacyFlatContext {
  return Object.assign(
    {},
    ...APP_SHELL_DOMAIN_CONTEXT_NAMES.map((name) => contexts[name]),
  );
}

export function flattenSelectedAppShellDomainContexts<
  TDomainName extends AppShellDomainContextName,
>(
  contexts: AppShellDomainContextSelection<TDomainName>,
  domainNames: readonly TDomainName[],
): AppShellLegacyFlatContext {
  return Object.assign({}, ...domainNames.map((name) => contexts[name]));
}

/**
 * 按 domain 对象身份缓存 flatten 结果。
 * 当 reuseStableAppShellDomainContexts 保住未变 domain 引用时，
 * flatten 不再每帧分配新 bag（层 4 协调/effect 输入更稳）。
 */
export type DomainFlattenIdentityCache = {
  domainValues: readonly unknown[] | null;
  flattened: AppShellLegacyFlatContext | null;
};

export function flattenSelectedAppShellDomainContextsMemoized<
  TDomainName extends AppShellDomainContextName,
>(
  contexts: AppShellDomainContextSelection<TDomainName>,
  domainNames: readonly TDomainName[],
  cache: DomainFlattenIdentityCache,
): AppShellLegacyFlatContext {
  const domainValues = domainNames.map((name) => contexts[name]);
  const previous = cache.domainValues;
  if (
    previous &&
    previous.length === domainValues.length &&
    previous.every((value, index) => Object.is(value, domainValues[index])) &&
    cache.flattened
  ) {
    return cache.flattened;
  }
  const flattened = Object.assign({}, ...domainValues) as AppShellLegacyFlatContext;
  cache.domainValues = domainValues;
  cache.flattened = flattened;
  return flattened;
}

/** 导出各 consumer 的 domain 选择集，供边界测试锁定，防止回潮成「全量 flatten」。 */
export const APP_SHELL_CONSUMER_DOMAIN_SELECTION = {
  layoutNodes: [
    "runtimeThreadContext",
    "sessionIdentityContext",
    "workspaceCatalogContext",
    "gitSurfaceContext",
    "modeRoutingContext",
    "accountSurfaceContext",
    "dictationSurfaceContext",
    "workspaceNavigationContext",
    "composerContext",
    "layoutContext",
    "fileEditorContext",
    "settingsContext",
    "runtimeContext",
    "modelSelectionContext",
    "collaborationModeContext",
  ],
  sections: [
    "sessionIdentityContext",
    "workspaceCatalogContext",
    "gitSurfaceContext",
    "modeRoutingContext",
    "accountSurfaceContext",
    "dictationSurfaceContext",
    "workspaceNavigationContext",
    "composerContext",
    "layoutContext",
    "fileEditorContext",
    "settingsContext",
  ],
  render: [
    "sessionIdentityContext",
    "workspaceCatalogContext",
    "gitSurfaceContext",
    "modeRoutingContext",
    "accountSurfaceContext",
    "dictationSurfaceContext",
    "workspaceNavigationContext",
    "composerContext",
    "layoutContext",
    "fileEditorContext",
    "settingsContext",
    "runtimeContext",
  ],
} as const satisfies Record<string, readonly AppShellDomainContextName[]>;

/**
 * @deprecated 生产路径请用 `bindAppShellDomainBag`（selectAppShellDomainBag.ts）。
 * 保留实现以便测试与 legacy 门面 re-export。
 */
export function adaptAppShellLegacyFlatContext<TBoundary extends object>(
  context: AppShellLegacyFlatContext,
): TBoundary {
  return context as TBoundary;
}

function areAppShellDomainContextValuesShallowEqual(
  left: AppShellDomainContextValue,
  right: AppShellDomainContextValue,
): boolean {
  if (Object.is(left, right)) {
    return true;
  }
  const leftKeys = Object.keys(left);
  const rightKeys = Object.keys(right);
  if (leftKeys.length !== rightKeys.length) {
    return false;
  }
  return leftKeys.every((key) => Object.is(left[key], right[key]));
}

export function reuseStableAppShellDomainContexts(
  previousContexts: AppShellDomainContexts | null | undefined,
  nextContexts: AppShellDomainContexts,
): AppShellDomainContexts {
  if (!previousContexts) {
    return nextContexts;
  }
  const stable = {} as AppShellDomainContexts;
  for (const domainName of APP_SHELL_DOMAIN_CONTEXT_NAMES) {
    stable[domainName] = areAppShellDomainContextValuesShallowEqual(
      previousContexts[domainName],
      nextContexts[domainName],
    )
      ? previousContexts[domainName]
      : nextContexts[domainName];
  }
  return stable;
}

export function findOverlappingAppShellDomainKeys(): string[] {
  const keyOwners = new Map<string, AppShellDomainContextName>();
  const overlappingKeys = new Set<string>();
  for (const domainName of APP_SHELL_DOMAIN_CONTEXT_NAMES) {
    for (const key of APP_SHELL_DOMAIN_CONTEXT_OWNED_KEYS[domainName]) {
      const previousOwner = keyOwners.get(key);
      if (previousOwner && previousOwner !== domainName) {
        overlappingKeys.add(key);
      } else {
        keyOwners.set(key, domainName);
      }
    }
  }
  return [...overlappingKeys].sort();
}
