// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/providers.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/providers.ts; keys mirror the English source.
const providers = {
  "providers": {
    "localConfig": "Configuração local",
    "claude": {
      "label": "Claude Code"
    },
    "codex": {
      "label": "Codex CLI"
    },
    "gemini": {
      "label": "Gemini CLI"
    },
    "kimi": {
      "label": "Kimi CLI"
    },
    "grok": {
      "label": "Grok CLI"
    },
    "opencode": {
      "label": "OpenCode"
    },
    "pi": {
      "label": "PI CLI"
    }
  }
};

export default providers;
