// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
const tools = {
  "tools": {
    "readFile": "फ़ाइल पढ़ें",
    "readDirectory": "डायरेक्टरी पढ़ें",
    "editFile": "फ़ाइल संपादित करें",
    "writeFile": "फ़ाइल लिखें",
    "editNotebook": "नोटबुक संपादित करें",
    "runCommand": "कमांड चलाएं",
    "executeCommand": "कमांड निष्पादित करें",
    "terminal": "Terminal",
    "terminalCommand": "Terminal command",
    "terminalRunning": "Running…",
    "commandLabel": "Command",
    "outputLabel": "Output",
    "outputLineCount": "{{count}} lines",
    "noOutput": "No output",
    "bashGroupCount": "{{count}} commands",
    "search": "खोजें",
    "fileMatch": "फ़ाइल मिलान",
    "findFile": "फ़ाइल खोजें",
    "webFetch": "वेब फ़ेच",
    "webSearch": "वेब खोज",
    "subtask": "उपकार्य",
    "todoList": "टूडू सूची",
    "userInputRequest": "उपयोगकर्ता से प्रश्न पूछें",
    "diffCompare": "Diff",
    "result": "परिणाम",
    "claudeControlResumeFailed": "Resume विफल हुआ",
    "claudeControlModelChanged": "मॉडल बदला गया",
    "claudeControlInterrupted": "बाधित हुआ",
    "claudeControlLocalOutput": "स्थानीय कमांड आउटपुट",
    "webRequest": "वेब अनुरोध",
    "batchRun": "बैच रन",
    "searchMatch": "खोज/मिलान",
    "batchReadFile": "बैच में {{count}} फ़ाइलें पढ़ें",
    "batchSearch": "बैच खोज",
    "batchSearchMatch": "बैच खोज/मिलान",
    "batchEditFile": "बैच फ़ाइलें संपादित करें",
    "fileEditSceneCount": "बैच में {{count}} फ़ाइलें संपादित करें",
    "fileEditSceneToggle": "बैच में {{count}} फ़ाइलें संपादित करें, विवरण दिखाएँ/छिपाएँ",
    "bashGroupBatchRun": "बैच रन कमांड",
    "bashGroupCompleted": "पूर्ण",
    "bashGroupAllCompleted": "सभी पूर्ण",
    "bashGroupFailed": "विफल",
    "planQuickView": "योजना",
    "openFullPlanPanel": "पूरा योजना पैनल खोलें",
    "closePlanPanel": "योजना पैनल बंद करें",
    "path": "पथ",
    "lineRange": "पंक्ति {{start}}-{{end}}",
    "failedCount": "{{count}} विफल"
  }
};

export default tools;
